<div class="main-container product">
  <div class="main wrapper clearfix">
    <div class="productleft">
      <h1>Rhino Ecoclear</h1>
      <h4>High performance waste water treatment system</h4>
    </div>
    <div class="productright one">
      <img src="http://renewgroupuk.com/wheelwash/img/ecoclear-logo.png" />
    </div>
    <div class="productleft">
      <p><b>The Ecoclear waste water treatment system is the best performing lamella clarifier designed for use in wheel washing applications. It has been developed in collaboration with Scott Vickers Pte, the creators of the Cleartec range of systems which have been successfully cleaning waste and surface water from construction sites for many years, worldwide.</b></p>
      <p>The Ecoclear effectively removes suspended solids from the waste water generated by wheel washing operations. Although it only requires an area of 12m2, the Ecoclear has an effective settlement capacity exceeding 200m2, which enables clarifying the waste water to a similar quality as if it had flowed through 16 standard settlement tanks in a row or 2 standard lagoons. This enables high quality recycled water to be re-used in the wheel washing process, thus maximising performance.</p>
      <p>The incoming waste water enters the Ecoclear system via a primary tank. This slows the water down and settles out the heaviest solids with the aid of 2 inclined steel plates fitted internally. The water then flows into the clarifying section where the lamella blocks are situated. The quality of the treated water is attributed to the large internal surface area created by the lamella blocks located in this chamber. They provide 192m2 of sloping surfaces for the suspended solids to contact. Once contacted, the solids collect on the lamella blocks then sink down to the hopper in the base forming sludge. The hopper is fitted with a knife valve for easy emptying. Meanwhile, clean water rises to the top of the chamber and weirs over into a header tank.</p>
      <p>The Ecoclear is supplied with steel lids that cover the top of the unit. This prevents blockages from falling debris or foliage entering the system. The lids are easy to open for access into the lamella chamber. Access is only required periodically to wash down the lamella blocks to maximise performance.</p>
      <p>The Ecoclear works effectively without the need for chemical treatment and requires only a flat, level hardstanding. The unit can be quickly and easily set up in conjunction with a Wheelwash- supplied system or retrospectively fitted to others.</p>
      <p>Wheelwash also supplies the full range of Cleartec waste water treatment systems for treating waste and surface water from construction sites, enabling safe discharge into public drains.</p>
    </div>
    <div class="productright">
      <ul>
        <li><img src='http://renewgroupuk.com/wheelwash/img/icon-4.png' />No Power</li>
        <li><img src='http://renewgroupuk.com/wheelwash/img/icon-1.png' />=200m<sup>2</sup> recycling capacity</li>
        <li><img src='http://renewgroupuk.com/wheelwash/img/icon-3.png' />No Operator</li>
        <li style="border-width: 0 0 9px 0;"><img src='http://renewgroupuk.com/wheelwash/img/icon-6.png' />Mobile</li>
        <li><img src='http://renewgroupuk.com/wheelwash/img/icon-5.png' />No Civils</li>
      </ul>
    </div>
    <div class="line"></div>
    <div class="productimage"> <img src="../img/ecoclear-1.jpg" /> </div>
    <div class="specifications">
      <table>
        <tbody>
          <tr>
            <td>Primary Tank</td>
            <td>2000mm x 4000mm x 2000mm<br />
              16,000 l capacity </td>
          </tr>
          <tr>
            <td>Secondary Tank</td>
            <td>4000mm x 1800mm x 2500mm = 192m<sup>2</sup></td>
          </tr>
          <tr>
            <td>Header Tank</td>
            <td>2000mm x 2000mm x 4000mm<br />
              12,000 l capacity/td> 
          </tr>
          <tr>
            <td>Total Capacity</td>
            <td>200m<sup>2</sup><br />
              =16 settlement tanks<br />
              = 2 lagoons</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="line"></div>
    <div class="productbottomleft">
      <ul>
        <li><img src="../img/ecoclear-2.jpg" />Lamella blocks provide a large surface area for effective solids removal</li>
        <li><img src="../img/ecoclear-3.jpg" />Autohopper discharge valves for automatic emptying</li>
        <li><img src="../img/ecoclear-4.jpg" />Covered hinged walkway </li>
        <li><img src="../img/ecoclear-5.jpg" />Quality recycled water</li>
      </ul>
      <a href="Rhino%20Ecoclear.pdf" class="button download" target="_blank">Download PDF</a> <a href="http://renewgroupuk.com/wheelwash/product" class="button">See all products</a> <a href="http://renewgroupuk.com/wheelwash/contact" class="button">Contact Us</a>
    </div>
    <div class="productbottomright">
      <h4>Customer Requirements</h4>
      <ul>
        <li>Clear lifting zone for offloading with Hiab</li>
        <li>Compacted level hardcore or concrete/tarmac base for the system and associated ramps and tanks</li>
        <li>Nominated site personnel to be available for training</li>
      </ul>
    </div>
    <div class="productbottom">
      <div> <img src="../img/madeinbritain.png" /> <img src="../img/iso.png" /> </div>
      <p>* All weights are approximate dry weights. Wheelwash Limited reserves the right to change detailed specifications from time to time. Drawings are to show indicative layouts only and are not to scale. Specifications are based on supply within the UK, please ask for details outside of this location. Specifications may vary when systems supplied as rental units.<br />
        ** Optional</p>
    </div>
  </div>
</div>
